In [1]:
import veloxchem as vlx
import numpy as np
from numpy.linalg import inv

np.set_printoptions(precision=4, suppress=True, linewidth=200)

mol_str = """
F        0.00000000    0.00000000     -0.1733
H        0.00000000    0.00000000      1.5597
"""

molecule = vlx.Molecule.read_molecule_string(mol_str, units='au')
basis = vlx.MolecularBasis.read(molecule, "ANO-S-VDZP")

natoms = molecule.number_of_atoms()
norb = basis.get_dimensions_of_basis()

# SCF optimization
scf_drv = vlx.ScfRestrictedDriver()
scf_results = scf_drv.compute(molecule, basis)

# LoProp
loprop_drv = vlx.PEForceFieldGenerator()
loprop_out = loprop_drv.compute(molecule, basis, scf_results)

                                                                                                                          
                                            Self Consistent Field Driver Setup                                            
                                                                                                                          
                   Wave Function Model             : Spin-Restricted Hartree-Fock                                         
                   Initial Guess Model             : Superposition of Atomic Densities                                    
                   Convergence Accelerator         : Two Level Direct Inversion of Iterative Subspace                     
                   Max. Number of Iterations       : 50                                                                   
                   Max. Number of Error Vectors    : 10                                                                   
                

* Info * Orthogonalization matrix computed in 0.00 sec.                                                                   
                                                                                                                          


* Info * Starting Reduced Basis SCF calculation...                                                                        
* Info * ...done. SCF energy in reduced basis set: -100.012766838453 a.u. Time: 0.12 sec.                                 
                                                                                                                          


* Info * Overlap matrix computed in 0.00 sec.                                                                             
                                                                                                                          
* Info * Kinetic energy matrix computed in 0.00 sec.                                                                      
                                                                                                                          
* Info * Nuclear potential matrix computed in 0.00 sec.                                                                   
                                                                                                                          


* Info * Orthogonalization matrix computed in 0.00 sec.                                                                   
                                                                                                                          


                                                                                                                          
               Iter. | Hartree-Fock Energy | Energy Change | Gradient Norm | Max. Gradient | Density Change               
               --------------------------------------------------------------------------------------------               
                  1      -100.044454834060    0.0000000000      0.09590452      0.01454024      0.00000000                


                  2      -100.045516993811   -0.0010621598      0.02496179      0.00381084      0.02916094                


                  3      -100.045610410444   -0.0000934166      0.00916415      0.00129109      0.00845562                


                  4      -100.045620070317   -0.0000096599      0.00498811      0.00090086      0.00321571                


                  5      -100.045622986899   -0.0000029166      0.00038100      0.00005262      0.00129389                


                  6      -100.045623017384   -0.0000000305      0.00004308      0.00000686      0.00015367                


                  7      -100.045623017702   -0.0000000003      0.00000141      0.00000017      0.00001440                


                  8      -100.045623017702   -0.0000000000      0.00000013      0.00000002      0.00000069                


                                                                                                                          
               *** SCF converged in 8 iterations. Time: 0.59 sec.                                                         
                                                                                                                          


               Spin-Restricted Hartree-Fock:                                                                              
               -----------------------------                                                                              
               Total Energy                       :     -100.0456230177 a.u.                                              
               Electronic Energy                  :     -105.2389294228 a.u.                                              
               Nuclear Repulsion Energy           :        5.1933064051 a.u.                                              
               ------------------------------------                                                                       
               Gradient Norm                      :        0.0000001298 a.u.                                              
                                                                                                                          
                

                                                                                                                          
                                                Ground State Dipole Moment                                                
                                               ----------------------------                                               
                                                                                                                          
                                   X   :        -0.000000 a.u.        -0.000000 Debye                                     
                                   Y   :         0.000000 a.u.         0.000000 Debye                                     
                                   Z   :         0.765876 a.u.         1.946662 Debye                                     
                                 Total :         0.765876 a.u.         1.946662 Debye                                     
                

                                                                                                                          
                                               Linear Response Solver Setup                                               
                                                                                                                          
                               Number of Frequencies           : 1                                                        
                               Max. Number of Iterations       : 150                                                      
                               Convergence Threshold           : 1.0e-04                                                  
                               ERI Screening Threshold         : 1.0e-12                                                  
                                                                                                                          


* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 3 ungerade trial vectors in reduced space                                                                        
                                                                                                                          
* Info * 8.96 kB of memory used for subspace procedure on the master node                                                 
* Info * 1.79 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   1 * Residuals (Max,Min): 9.39e-01 and 7.79e-01                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 6 ungerade trial vectors in reduced space                                                                        
                                                                                                                          
* Info * 12.32 kB of memory used for subspace procedure on the master node                                                
* Info * 1.87 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   2 * Residuals (Max,Min): 2.72e-01 and 1.28e-01                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 9 ungerade trial vectors in reduced space                                                                        
                                                                                                                          
* Info * 15.68 kB of memory used for subspace procedure on the master node                                                
* Info * 1.87 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   3 * Residuals (Max,Min): 7.04e-02 and 2.99e-02                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 12 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 19.04 kB of memory used for subspace procedure on the master node                                                
* Info * 1.87 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   4 * Residuals (Max,Min): 1.27e-02 and 6.76e-03                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 15 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 22.40 kB of memory used for subspace procedure on the master node                                                
* Info * 1.87 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   5 * Residuals (Max,Min): 1.61e-03 and 8.15e-04                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 18 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 25.95 kB of memory used for subspace procedure on the master node                                                
* Info * 1.87 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   6 * Residuals (Max,Min): 1.41e-04 and 4.76e-05                                            
                

* Info * Processing 1 Fock build...                                                                                       


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 19 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 26.88 kB of memory used for subspace procedure on the master node                                                
* Info * 1.87 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   7 * Residuals (Max,Min): 4.76e-05 and 1.17e-05                                            
                

               *** Linear response converged in 7 iterations. Time: 1.24 sec                                              
                                                                                                                          
                                                                                                                          


               Polarizability (w=0.0000)                                                                                  
               -------------------------                                                                                  
                                  X              Y              Z                                                         
               X         2.67753966    -0.00000000     0.00000000                                                         
               Y        -0.00000000     2.67753966     0.00000000                                                         
               Z         0.00000000     0.00000000     4.57430669                                                         
                                                                                                                          


                                                                                                                          
                                                Local Properties (LoProp)                                                 
                                                                                                                          
         Reference: L. Gagliardi, R. Lindh, G. Karlström, J. Chem. Phys. 2004, 121, 4494-4500.
                                                                                                                          


                                                Molecular Polarizabilities                                                
                                                --------------------------                                                
                                                 alpha_xx :       2.6775                                                  
                                                 alpha_yy :       2.6775                                                  
                                                 alpha_zz :       4.5743                                                  
                                                                                                                          
                                              Atomic Partial Charges (a.u.)                                               
                                              -----------------------------                                               
                

In [2]:
print("Localized charges (a.u.):")
print(f"F: {loprop_out['localized_charges'][0] : .4f}")
print(f"H: {loprop_out['localized_charges'][1] : .4f}")

print("\nLocalized polarizabilities (a.u.):")
print("     xx      xy      xz      yy      yz      zz")
print(f"F: {loprop_out['localized_polarizabilities'][0]}")
print(f"H: {loprop_out['localized_polarizabilities'][1]}")

Localized charges (a.u.):
F: -0.4445
H:  0.4445

Localized polarizabilities (a.u.):
     xx      xy      xz      yy      yz      zz
F: [ 1.689   0.     -0.      1.689   0.      2.6143]
H: [ 0.9885 -0.      0.      0.9885  0.      1.96  ]


In [3]:
S = scf_results['S']

print(S)

[[ 1.      0.     -0.      0.0567  0.0139  0.      0.      0.      0.      0.     -0.1091  0.      0.      0.      0.      0.      0.      0.      0.    ]
 [ 0.      1.     -0.      0.4804  0.1061  0.      0.      0.      0.      0.     -0.5499  0.      0.      0.      0.      0.      0.      0.      0.    ]
 [-0.     -0.      1.      0.4489  0.243   0.      0.      0.      0.      0.     -0.0698  0.      0.      0.      0.      0.      0.      0.      0.    ]
 [ 0.0567  0.4804  0.4489  1.      0.      0.      0.      0.      0.3972  0.4244  0.      0.      0.      0.      0.      0.      0.2177  0.      0.    ]
 [ 0.0139  0.1061  0.243   0.      1.      0.      0.      0.     -0.2151 -0.0151  0.      0.      0.      0.      0.      0.     -0.244   0.      0.    ]
 [ 0.      0.      0.      0.      0.      1.      0.      0.3993  0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.      1.      0.4209  0. 

In [4]:
rearranged_indices = vlx.aoindices.get_basis_function_indices_of_atoms(molecule, basis)

print('Rearranged AO indices：', rearranged_indices)

Rearranged AO indices： [0, 1, 2, 11, 5, 8, 12, 6, 9, 14, 15, 16, 17, 18, 3, 4, 13, 7, 10]


In [5]:
T0 = np.zeros((norb, norb))

for col, row in enumerate(rearranged_indices):
    T0[row, col] = 1

S0 = np.einsum('ba,bc,cd->ad', T0, S, T0)
print(S0)

[[ 1.      0.     -0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.0567  0.0139  0.      0.     -0.1091]
 [ 0.      1.     -0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.4804  0.1061  0.      0.     -0.5499]
 [-0.     -0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.4489  0.243   0.      0.     -0.0698]
 [ 0.      0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.3993  0.      0.    ]
 [ 0.      0.      0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.3993  0.    ]
 [ 0.      0.      0.      0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.3972 -0.2151  0.      0.     -0.1471]
 [ 0.      0.      0.      0.      0.      0.      1.      0.      0. 

In [6]:
T1 = np.zeros((norb,norb))

norb_per_atom, indices_occ, indices_virt = loprop_drv.get_ao_indices(molecule, basis)

print('Occupied orbitals:', indices_occ)
print('Virtual orbitals:', indices_virt, '\n')

ri = 0
for atom in range(natoms):

    rf = ri + norb_per_atom[atom]

    L = np.linalg.cholesky(S0[ri:rf, ri:rf])
    T1[ri:rf, ri:rf] = np.linalg.inv(L.T)

    ri += norb_per_atom[atom]

S1 = np.einsum('ba,bc,cd->ad', T1, S0, T1)
print(S1)

Occupied orbitals: [0, 1, 3, 4, 5, 14]
Virtual orbitals: [2, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18] 

[[ 1.     -0.     -0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.0567  0.0139  0.      0.     -0.1091]
 [-0.      1.     -0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.4804  0.1061  0.      0.     -0.5499]
 [ 0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.4489  0.243   0.      0.     -0.0698]
 [ 0.      0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.3993  0.      0.    ]
 [ 0.      0.      0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.3993  0.    ]
 [ 0.      0.      0.      0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.3

In [7]:
T2 = np.zeros((norb, norb))

S1_oo = S1[indices_occ, :][:, indices_occ]
T2_oo = loprop_drv.lowdin_orthonormalize(S1_oo)

nocc = len(indices_occ)
nvirt = len(indices_virt)

for r in range(nocc):
    for c in range(nocc):
        T2[indices_occ[r], indices_occ[c]] = T2_oo[r, c]

S1_vv = S1[indices_virt, :][:, indices_virt]
T2_vv = loprop_drv.lowdin_orthonormalize(S1_vv)

for r in range(nvirt):
    for c in range(nvirt):
        T2[indices_virt[r], indices_virt[c]] = T2_vv[r, c]
        
S2 = np.einsum('ba,bc,cd->ad', T2, S1, T2)
print(S2)

[[ 1.      0.     -0.0238  0.      0.     -0.      0.      0.      0.0032  0.     -0.     -0.0057  0.     -0.     -0.      0.0158  0.     -0.     -0.122 ]
 [ 0.      1.     -0.1851  0.      0.      0.      0.      0.     -0.0354  0.     -0.     -0.0524  0.     -0.     -0.      0.1174 -0.     -0.     -0.644 ]
 [-0.0238 -0.1851  1.     -0.     -0.     -0.1009  0.     -0.      0.     -0.      0.      0.     -0.      0.      0.551   0.      0.     -0.     -0.    ]
 [ 0.      0.     -0.      1.      0.      0.     -0.1057 -0.     -0.      0.     -0.     -0.     -0.0912 -0.     -0.     -0.      0.4597  0.     -0.    ]
 [ 0.      0.     -0.      0.      1.      0.      0.     -0.1057  0.     -0.     -0.0912 -0.      0.     -0.      0.     -0.      0.      0.4597  0.    ]
 [-0.      0.     -0.1009  0.      0.      1.     -0.      0.     -0.0841  0.     -0.     -0.0855  0.     -0.     -0.     -0.2239  0.     -0.     -0.2088]
 [ 0.      0.      0.     -0.1057  0.     -0.      1.      0.     -0. 

In [8]:
T3 = np.identity(norb)

S2_ov = S2[indices_occ, :][:, indices_virt]

for i, index_occ in enumerate(indices_occ):
    for j, index_virt in enumerate(indices_virt):
        T3[index_occ, index_virt] = - S2_ov[i, j]

S3 = np.einsum('ba,bc,cd->ad', T3, S2, T3)
print(S3)

[[ 1.      0.      0.      0.      0.     -0.      0.     -0.     -0.     -0.      0.     -0.      0.      0.     -0.     -0.     -0.     -0.      0.    ]
 [ 0.      1.      0.      0.      0.      0.      0.     -0.      0.     -0.      0.      0.      0.      0.     -0.      0.     -0.     -0.      0.    ]
 [ 0.      0.      0.6514  0.      0.      0.      0.     -0.     -0.2858 -0.      0.     -0.1614 -0.     -0.     -0.      0.0049 -0.     -0.     -0.2348]
 [ 0.      0.      0.      1.      0.      0.      0.     -0.      0.     -0.      0.      0.      0.      0.     -0.      0.     -0.     -0.      0.    ]
 [ 0.      0.      0.      0.      1.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.    ]
 [-0.      0.      0.      0.      0.      1.      0.     -0.      0.     -0.      0.      0.      0.      0.     -0.     -0.     -0.     -0.      0.    ]
 [ 0.      0.      0.      0.     -0.      0.      0.9888  0.     -0. 

In [9]:
T4 = np.identity(norb)

S3_vv = S3[indices_virt, :][:, indices_virt]
T4_vv = loprop_drv.lowdin_orthonormalize(S3_vv)

for i, index_virt1 in enumerate(indices_virt):
    for j, index_virt2 in enumerate(indices_virt):
        T4[index_virt1, index_virt2] = T4_vv[i, j]
        
S4 = np.einsum('ba,bc,cd->ad', T4, S3, T4)
print(S4)

[[ 1.  0.  0.  0.  0. -0.  0.  0.  0. -0. -0.  0.  0. -0. -0. -0. -0. -0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0. -0. -0.  0. -0. -0.  0.]
 [ 0.  0.  1.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0. -0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0. -0.  0.  0. -0. -0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0.  0.  0.  0.  0.  1.  0.  0.  0.  0. -0.  0.  0. -0. -0. -0. -0. -0.  0.]
 [ 0.  0. -0.  0.  0.  0.  1. -0. -0.  0.  0.  0.  0. -0. -0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -0.  0. -0.  1.  0.  0.  0. -0.  0. -0. -0. -0.  0. -0. -0.]
 [ 0.  0.  0.  0. -0.  0. -0.  0.  1. -0. -0. -0.  0. -0. -0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0. -0.  0.  0.  0. -0.  1.  0.  0.  0. -0. -0. -0.  0.  0. -0.]
 [-0. -0.  0. -0. -0. -0.  0.  0. -0.  0.  1.  0. -0. -0.  0.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  1.  0.  0. -0. -0.  0. -0.  0.]
 [ 0.  0.  0.  0. -0.  0.  0.  0.  0.  0. -0.  0.  1

In [10]:
T = np.einsum('ab,bc,cd,de,ef->af', T0, T1, T2, T3, T4)

In [11]:
print('   F 1s    F 2s    F 2px   F 2py   F 2pz   H 1s\n', '-'*49)
print(T[:,indices_occ])

   F 1s    F 2s    F 2px   F 2py   F 2pz   H 1s
 -------------------------------------------------
[[ 1.0017  0.0146  0.      0.      0.012  -0.0385]
 [ 0.0146  1.1235  0.      0.      0.1021 -0.3264]
 [ 0.      0.      0.      0.      0.      0.    ]
 [-0.0385 -0.3264 -0.      0.     -0.2699  1.2096]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      1.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.012   0.1021  0.      0.      1.0844 -0.2699]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      1.      0.      0.     -0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.     

In [12]:
def atomic_property(Omega, D):
    
    Omega_AB = np.zeros((natoms, natoms))

    Omega_L = np.einsum('ba,bc,cd->ad', T, Omega, T)
    D_L = np.einsum('ab,bc,dc->ad', inv(T), D, inv(T))
    
    idx_A = 0
    for A in range(natoms):

        idx_B = 0
        for B in range(natoms):
            
            P = Omega_L[idx_A : idx_A + norb_per_atom[A], idx_B : idx_B + norb_per_atom[B]]
            Q = D_L[idx_A : idx_A + norb_per_atom[A], idx_B : idx_B + norb_per_atom[B]]
        
            Omega_AB[A,B] = np.matmul(P.T, Q).trace()
                    
            idx_B += norb_per_atom[B]
            
        idx_A += norb_per_atom[A]
        
    return Omega_AB

In [13]:
# atomic numbers and therefore nuclear charge in atomic units
Z_A = molecule.get_element_ids()
D = 2 * scf_results['D_alpha']

Q_A = - atomic_property(S, D).sum(axis = 1)
Q = Q_A.sum()

print(f"Total electronic charge: {Q : .4f}")
print(f"Localized atomic charges: {Q_A + Z_A}")

Total electronic charge: -10.0000
Localized atomic charges: [-0.4445  0.4445]


In [14]:
dipole_mats = vlx.compute_electric_dipole_integrals(molecule, basis)

mu = dipole_mats[2]  # mu_z

mu_AB = atomic_property(mu, D)

print(f'Total dipole moment: {mu_AB.sum() : .4f}')
print('\nmu_AB:\n', mu_AB)

Total dipole moment:  0.7659

mu_AB:
 [[ 1.9058 -0.1177]
 [-0.1177 -0.9045]]


In [15]:
R = np.zeros((natoms, natoms, 3))

coords = molecule.get_coordinates_in_bohr()

for A in range(natoms):
    for B in range(natoms):
    
        R[A,B,:] = (coords[A,:] + coords[B,:]) / 2

In [16]:
print('mu_(AB):\n', mu_AB - np.diag(Q_A) * R[:,:,2])

mu_(AB):
 [[ 0.269  -0.1177]
 [-0.1177 -0.0381]]


In [17]:
lrs_drv = vlx.LinearResponseSolver()
lrs_out = lrs_drv.compute(molecule, basis, scf_results)

                                                                                                                          
                                               Linear Response Solver Setup                                               
                                                                                                                          
                               Number of Frequencies           : 1                                                        
                               Max. Number of Iterations       : 150                                                      
                               Convergence Threshold           : 1.0e-04                                                  
                               ERI Screening Threshold         : 1.0e-12                                                  
                                                                                                                          


* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 3 ungerade trial vectors in reduced space                                                                        
                                                                                                                          
* Info * 8.96 kB of memory used for subspace procedure on the master node                                                 
* Info * 1.92 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   1 * Residuals (Max,Min): 9.39e-01 and 7.79e-01                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 6 ungerade trial vectors in reduced space                                                                        
                                                                                                                          
* Info * 12.32 kB of memory used for subspace procedure on the master node                                                
* Info * 1.92 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   2 * Residuals (Max,Min): 2.72e-01 and 1.28e-01                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 9 ungerade trial vectors in reduced space                                                                        
                                                                                                                          
* Info * 15.68 kB of memory used for subspace procedure on the master node                                                
* Info * 1.92 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   3 * Residuals (Max,Min): 7.04e-02 and 2.99e-02                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 12 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 19.04 kB of memory used for subspace procedure on the master node                                                
* Info * 1.92 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   4 * Residuals (Max,Min): 1.27e-02 and 6.76e-03                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 15 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 22.40 kB of memory used for subspace procedure on the master node                                                
* Info * 1.92 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   5 * Residuals (Max,Min): 1.61e-03 and 8.15e-04                                            
                

* Info * Processing 3 Fock builds...                                                                                      


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 18 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 25.95 kB of memory used for subspace procedure on the master node                                                
* Info * 1.92 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   6 * Residuals (Max,Min): 1.41e-04 and 4.76e-05                                            
                

* Info * Processing 1 Fock build...                                                                                       


                                                                                                                          
* Info * 0 gerade trial vectors in reduced space                                                                          
* Info * 19 ungerade trial vectors in reduced space                                                                       
                                                                                                                          
* Info * 26.88 kB of memory used for subspace procedure on the master node                                                
* Info * 1.92 GB of memory available for the solver on the master node                                                    
                                                                                                                          
               *** Iteration:   7 * Residuals (Max,Min): 4.76e-05 and 1.17e-05                                            
                

               *** Linear response converged in 7 iterations. Time: 1.32 sec                                              
                                                                                                                          
                                                                                                                          


               Polarizability (w=0.0000)                                                                                  
               -------------------------                                                                                  
                                  X              Y              Z                                                         
               X         2.67753966    -0.00000000     0.00000000                                                         
               Y        -0.00000000     2.67753966     0.00000000                                                         
               Z         0.00000000     0.00000000     4.57430669                                                         
                                                                                                                          


In [18]:
alpha = - lrs_out['response_functions'][('z', 'z', 0)]

print(f"Molecular polarizability (zz-component): {alpha : .4f} a.u.")

Molecular polarizability (zz-component):  4.5743 a.u.


In [19]:
def vec2mat(N, nocc, norb):
    
    n = nocc * (norb - nocc)
    
    kappa = np.zeros((norb,norb))
    
    kappa[:nocc, nocc:norb] = N[:n].reshape(nocc, norb - nocc)
    kappa[nocc:, :nocc] = - N[n:].reshape(nocc, norb - nocc).T
    
    return kappa

In [20]:
nocc = molecule.number_of_alpha_electrons()

solution_z_0 = lrs_drv.get_full_solution_vector(lrs_out['solutions'][('z', 0)])

N = solution_z_0

kappa = vec2mat(N, nocc, norb)

C = scf_results['C_alpha']
# factor of sqrt(2) due to use of normalized spin-adapted excitation operators
# in the formation of the property gradient, mu[1].
D1 = np.einsum('QP,aP,bQ->ab', kappa, C, C) * np.sqrt(2)

alpha_AB = atomic_property(mu, D1)

print(f"alpha = {alpha_AB.sum() : .6f} a.u.")
print('\nalpha_AB:\n', alpha_AB)

alpha =  4.574307 a.u.

alpha_AB:
 [[1.1175 0.6279]
 [0.6279 2.201 ]]


In [21]:
dQ_A = - atomic_property(S, D1).sum(axis = 1)

# Lower case atomic indices for gauge-origin independent properties
alpha_ab = alpha_AB - np.diag(dQ_A) * R[:,:,2]

print('dQ_A:\n', dQ_A)
print('alpha_(AB):\n', alpha_ab)

dQ_A:
 [-1.2534  1.2534]
alpha_(AB):
 [[0.9003 0.6279]
 [0.6279 0.246 ]]


In [22]:
def f(A, B):
    
    # Bragg-Slater radii for F and H
    bohr2ang = 0.529177249
    R_BS = np.array([0.50, 0.25]) / bohr2ang
    
    # interatomic distance
    dR_AB = np.linalg.norm(R[A,A,:] - R[B,B,:])
        
    return np.exp(2.0 * (dR_AB / (R_BS[A] + R_BS[B]))**2)

In [23]:
L_AB = np.zeros((natoms, natoms))

for A in range(natoms):
    for B in range(natoms):
        L_AB[A,B] = 0.5 / f(A,B)

    L_AB[A,A] -= sum(L_AB[A,:])

L_AB = L_AB + 2.0 * np.max(np.abs(L_AB))

lambda_A = np.linalg.solve(L_AB, dQ_A)

print(f'lambda_A: {lambda_A}')

lambda_A: [ 24.9315 -24.9315]


In [24]:
dQ_AB = np.zeros((natoms,natoms))

for A in range(natoms):
    for B in range(natoms):

        dQ_AB[A,B] = - 0.5 * (lambda_A[A] - lambda_A[B]) / f(A,B)

print(dQ_AB)

[[-0.     -1.2534]
 [ 1.2534 -0.    ]]


In [25]:
alpha_bond_AB = np.zeros((natoms, natoms))

for A in range(natoms):
    for B in range(natoms):
        alpha_bond_AB[A,B] = dQ_AB[A,B] * (R[A,A,2] - R[B,B,2])
        
print(alpha_bond_AB)

[[-0.      2.1722]
 [ 2.1722 -0.    ]]


In [26]:
alpha_A = (alpha_ab + 0.5 * alpha_bond_AB).sum(axis = 1)

print(f"LoProp atomic polarizabilities: {alpha_A}")
print(f"Molecular polarizability: {alpha_A.sum() : .4f} a.u.")

LoProp atomic polarizabilities: [2.6143 1.96  ]
Molecular polarizability:  4.5743 a.u.
