In [1]:
import veloxchem as vlx

mol_str = """2

C        0.00000000    0.00000000   -0.71500000
O        0.00000000    0.00000000    0.71500000
"""
molecule = vlx.Molecule.read_xyz_string(mol_str)
basis = vlx.MolecularBasis.read(molecule, "sto-3g", ostream=None)

scf_drv = vlx.ScfRestrictedDriver()
scf_drv.ostream.mute()
scf_results = scf_drv.compute(molecule, basis)

In [2]:
molecule.show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [3]:
import numpy as np

np.set_printoptions(precision=3, suppress=True, linewidth=170)

C = scf_results["C_alpha"]
print("MO coefficient matrix:\n", C)

MO coefficient matrix:
 [[ 0.001  0.994  0.091 -0.228 -0.109 -0.    -0.     0.    -0.     0.105]
 [-0.004  0.024 -0.26   0.836  0.47   0.     0.    -0.     0.    -0.536]
 [ 0.995  0.     0.231  0.114 -0.036  0.    -0.    -0.    -0.    -0.089]
 [ 0.023 -0.005 -0.856 -0.526  0.196 -0.     0.     0.     0.     0.547]
 [-0.     0.     0.     0.    -0.     0.01   0.431  0.911  0.049 -0.   ]
 [ 0.     0.    -0.    -0.    -0.     0.02   0.847 -0.547 -0.029  0.   ]
 [-0.004  0.004 -0.141 -0.003 -0.621  0.    -0.    -0.     0.    -0.942]
 [-0.003  0.002  0.112 -0.38   0.578 -0.     0.    -0.    -0.    -0.852]
 [ 0.    -0.    -0.     0.     0.     0.431 -0.01   0.049 -0.911 -0.   ]
 [ 0.     0.     0.    -0.     0.     0.847 -0.02  -0.029  0.547  0.   ]]


In [4]:
S = scf_results["S"]
print("Overlap matrix:\n", S)

Overlap matrix:
 [[ 1.     0.248  0.     0.017  0.     0.     0.    -0.031  0.     0.   ]
 [ 0.248  1.     0.022  0.255  0.     0.     0.    -0.251  0.     0.   ]
 [ 0.     0.022  1.     0.237  0.     0.     0.036  0.     0.     0.   ]
 [ 0.017  0.255  0.237  1.     0.     0.     0.337  0.     0.     0.   ]
 [ 0.     0.     0.     0.     1.     0.132  0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.132  1.     0.     0.     0.     0.   ]
 [ 0.     0.     0.036  0.337  0.     0.     1.    -0.285  0.     0.   ]
 [-0.031 -0.251  0.     0.     0.     0.    -0.285  1.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     1.     0.132]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.132  1.   ]]


In [5]:
basis = vlx.MolecularBasis.read(molecule, "cc-pVDZ", ostream=None)

In [6]:
print("Available basis sets for carbon:\n", basis.get_avail_basis("C"))

Available basis sets for carbon:
 ['6-31++G', '6-31++G*', '6-31++G**', '6-31+G', '6-31+G*', '6-31+G**', '6-311++G', '6-311++G(2D,2P)', '6-311++G(3DF,3PD)', '6-311++G*', '6-311++G**', '6-311+G', '6-311+G(2D,P)', '6-311+G*', '6-311+G**', '6-311G', '6-311G(2DF,2PD)', '6-311G*', '6-311G**', '6-31G', '6-31G(2DF,P)', '6-31G(3DF,3PD)', '6-31G*', '6-31G**', 'ANO-L-MB', 'ANO-L-VDZP', 'ANO-L-VQZP', 'ANO-L-VTZP', 'ANO-RCC-MB', 'ANO-S-MB', 'ANO-S-VDZP', 'AO-START-GUESS', 'AUG-CC-PCV5Z', 'AUG-CC-PCVDZ', 'AUG-CC-PCVQZ', 'AUG-CC-PCVTZ', 'AUG-CC-PV5Z', 'AUG-CC-PV6Z', 'AUG-CC-PVDZ', 'AUG-CC-PVQZ', 'AUG-CC-PVTZ', 'AUG-PCSEG-0', 'AUG-PCSEG-1', 'AUG-PCSEG-2', 'AUG-PCSEG-3', 'AUG-PCSEG-4', 'AUG-PCX-1', 'AUG-PCX-2', 'AUG-PCX-3', 'AUG-PCX-4', 'CC-PCV5Z', 'CC-PCVDZ', 'CC-PCVQZ', 'CC-PCVTZ', 'CC-PV5Z', 'CC-PV6Z', 'CC-PV6Z-NO-OPT-GC', 'CC-PVDZ', 'CC-PVQZ', 'CC-PVTZ', 'DAUG-CC-PCV5Z', 'DAUG-CC-PCVDZ', 'DAUG-CC-PCVQZ', 'DAUG-CC-PCVTZ', 'DAUG-CC-PV5Z', 'DAUG-CC-PV6Z', 'DAUG-CC-PVDZ', 'DAUG-CC-PVQZ', 'DAUG-CC-PVTZ'

In [7]:
nbas = basis.get_dimensions_of_basis()
nprim = basis.get_dimensions_of_primitive_basis()

print("Number of contracted basis functions:", nbas)
print("Number of primitive basis functions:", nprim)

Number of contracted basis functions: 28
Number of primitive basis functions: 68


In [8]:
label = basis.get_label()
print("Basis set label:", label)

Basis set label: CC-PVDZ


In [9]:
print(basis.get_string('Atomic Basis'))

               Molecular Basis (Atomic Basis)               

Basis: CC-PVDZ                                              

  Atom Contracted GTOs           Primitive GTOs                

  C     (3S,2P,1D)                (17S,4P,1D)                   
  O     (3S,2P,1D)                (17S,4P,1D)                   

Contracted Basis Functions : 28                             
Primitive Basis Functions  : 68                             


