In [1]:
import numpy as np

M = 10  # number of spin orbitals in our Fock space

In [2]:
class OccupationNumberVector:
    def __init__(self, occ_orbs=[]):
        self.phase = 1
        self.occ_num_vec = np.zeros(M, dtype=int)  # vacuum state

        for i in occ_orbs:
            self.occ_num_vec[i] = 1

    def __mul__(self, other):
        if np.array_equal(self.occ_num_vec, other.occ_num_vec):
            inner_prod = self.phase * other.phase
        else:
            inner_prod = 0

        return inner_prod

    def __str__(self):
        return (
            "phase: "
            + str(self.phase)
            + "\noccupation number vector: "
            + str(self.occ_num_vec)
        )

    def creation(self, p):
        if len(self.occ_num_vec) == 0:
            return

        if self.occ_num_vec[p] == 1:
            self.occ_num_vec = []
        else:
            self.phase *= np.prod((-1) ** self.occ_num_vec[:p])
            self.occ_num_vec[p] = 1

    def annihilation(self, p):
        if len(self.occ_num_vec) == 0:
            return

        if self.occ_num_vec[p] == 0:
            self.occ_num_vec = []
        else:
            self.phase *= np.prod((-1) ** self.occ_num_vec[:p])
            self.occ_num_vec[p] = 0

In [3]:
ket = OccupationNumberVector()

for i in [3, 2, 1, 0]:
    ket.creation(i)

print(ket)

phase: 1
occupation number vector: [1 1 1 1 0 0 0 0 0 0]


In [4]:
bra = OccupationNumberVector([0, 1, 2, 3])

D = np.zeros((M, M), dtype=int)

for p in range(M):
    for q in range(M):
        ket = OccupationNumberVector([0, 1, 2, 3])

        ket.annihilation(q)
        ket.creation(p)

        D[p, q] = bra * ket

print("One-particle denisty matrix:\n", D)

One-particle denisty matrix:
 [[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [5]:
bra = OccupationNumberVector([0, 1, 2, 3])

for p, q, r, s in [(0, 0, 1, 1), (0, 1, 1, 0), (0, 1, 0, 1)]:
    ket = OccupationNumberVector([0, 1, 2, 3])

    ket.annihilation(q)
    ket.annihilation(s)
    ket.creation(r)
    ket.creation(p)

    print("Two-particle density matrix element:", bra * ket)

Two-particle density matrix element: 1
Two-particle density matrix element: -1
Two-particle density matrix element: 0
